### ISSUE TITLE
Ambiguity on docs for .set()

### ISSUE THREAD

**Issue by thanpolas** [jpodwys/cache-service#15]
As per the docs:

> .set(key, value, [expiraiton], [refresh(key, cb)], [callback])

`expiration` and `refresh` are optional, so effectively one could write:

```js
cs.set('key', 'value', function(err, res) {});
```

However that is not the case as the callback will never be invoked.

**Comment by jpodwys** [comment]
This is a problem with the code not the documentation. It appears that I'm not assigning the callback when only 3 arguments are passed.

**Comment by jpodwys** [comment]
It seems I spoke too soon. Because both are functions and both accept they same number of arguments, I can't determine which is which. I'll updates the docs.

**Comment by jpodwys** [comment]
I created a branch to try to fix the issue you listed above both by adjusting the code and by adding documentation. Please have a look at [the diff](https://github.com/jpodwys/cache-service/compare/set-argument-list-fixes?expand=1) and let me know what you think.

**Comment by thanpolas** [comment]
yup, that's what should be done for this case... Let's continue this discussion on jpodwys/cache-service#19

**Comment by jpodwys** [comment]
`.set()` fixed and readme updated in `1.3.6`.
