### ISSUE TITLE
Clarify accepted values for set()

### ISSUE THREAD

**Issue by thanpolas** [jpodwys/cache-service#17]
Through testing I discovered that set() accepts an Object literal and get() returns it...

likewise when i set() a JSON stringified object, on get() I get an object literal (vs the stringified version)

How does this work? Make a note on README?

**Comment by jpodwys** [comment]
Good point. I'll document it.

**Comment by jpodwys** [comment]
I've [updated the readme](https://github.com/jpodwys/cache-service/commit/16215ecae954475bb23f77466510484f8c63cd90) to detail the behavior you noted in this issue.

**Comment by thanpolas** [comment]
nice, thanks!
