### ISSUE TITLE
refresh interval duration sets to 1' after first tick

### ISSUE THREAD

**Issue by thanpolas** [jpodwys/cache-service#18]
I have a `300` second (5 minute) default expiration set on both the redis store...

When I use `set()` with the `refresh` callback, the first time the refresh callback will be invoked is 5 minutes after the set was defined.

Every other refresh callback invocation will happen in 1 minute intervals

**Comment by jpodwys** [comment]
Are you referring to background refresh?

**Comment by thanpolas** [comment]
yes

**Comment by jpodwys** [comment]
The cache-service-redis PR merge referenced above needs to be duplicated to cache-service-cache-module and cache-service-node-cache.

**Comment by jpodwys** [comment]
After looking at the source for cache-service-cache-module and cache-service-node-cache, it appears that neither of them have the background refresh issue cache-service-redis had. Closing the issue.
