### ISSUE TITLE
Redis and node-cache shouldn't be package dependencies

### ISSUE THREAD

**Issue by nickdaugherty** [jpodwys/cache-service#8]
Having them as dependencies reduces the flexibility of the package and increases bloat.

The main place this presents a problem is when using `superagent-cache` (which has `cache-service` as a dependency) from the browser - installing both `redis` and `node-cache` is not workable for the package to be used in a browser environment.

**Comment by jpodwys** [comment]
Thanks for the wise feedback! So just to be sure, you're recommending that nodeCacheModule and redisCacheModule and their associated tests be moved to separate repos and then you'll just add whichever one you want to use to your package.json?

**Comment by nickdaugherty** [comment]
That would probably make the most sense - it would make the cache engines more pluggable and standalone, and make `cache-service` more lightweight.

**Comment by jpodwys** [comment]
Are you needing this update by any specific date?

**Comment by nickdaugherty** [comment]
Nope - it's more a 'nice to have' to allow this to work in the browser better. This is a cool project! I may write a cache backend for the browser, using localStorage, etc.

**Comment by jpodwys** [comment]
Thanks! It's a good idea to break the cache modules out. I'll be thinking about implementation for a bit and should be able to start development in no more than couple of weeks when another project I'm working on slows down. I'd love to chat about a local storage cache module with you when I finish.

**Comment by jpodwys** [comment]
So I'm starting on this update today, although I may not be lightning fast on completion since you have no deadline. Just curious, are you using superagent-cache or cache-service?

**Comment by jpodwys** [comment]
I'm actually making a lot of fast progress right now. Question: cache-service currently provides a default configuration which means it bundles in a cache module if you instantiate it without providing one. Do you think there's any benefit in this for people who simple want to get caching without worrying about configuration? Or should the implementer be required to always provide a cache module explicitly so that there is no extra bloat in the download?

**Comment by jpodwys** [comment]
Check out the branch with your feature addition and let me know what you think: https://github.com/jpodwys/cache-service/tree/breaking_out_cache_modules

**Comment by jpodwys** [comment]
Fixed in `1.1.0`. I'd love to see a cache backend for the browser like you mentioned earlier.
